# This is a basic workflow to help you get started with Actions

name: Continuous integration
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout
        run: | 
          echo checkout

      - name: Java version
        run: |
          java -version

      - name: Build docker image test
        run : | 
          docker build --target test --tag image:test .

      - name: Run tests
        if: success()
        run : |
          docker run -it image:test

      - name: Build docker image production
        run : |
          docker build --target prod --tage image:prod .

      - name: Run production
        run: |
          docker run -it image:prod
